import axiosClient from './api/axiosClient';
import { API_ENDPOINTS } from './api/endpoints';
import type { ApiResponse } from '../shared/types/api.types';
import type { StockMovementRecord, StockMovementType } from '../shared/types/inventoryProduct.types';

export type StockMovementLinePayload = {
  productId: string;
  quantity: number;
  unitCost?: number;
};

export type StockMovementPayload = {
  documentNo?: string;
  autoGenerateDocumentNo?: boolean;
  movementDate: string;
  warehouseId: string;
  supplierId?: string;
  referenceNo?: string;
  notes?: string;
  lines: StockMovementLinePayload[];
};

const endpointsFor = (movementType: StockMovementType) =>
  movementType === 'in' ? API_ENDPOINTS.STOCK_IN : API_ENDPOINTS.STOCK_OUT;

export const stockMovementService = {
  async getAll(movementType: StockMovementType): Promise<StockMovementRecord[]> {
    const response = await axiosClient.get<ApiResponse<{ items: StockMovementRecord[] }>>(
      endpointsFor(movementType).LIST
    );
    return response.data.data?.items ?? [];
  },

  async getById(movementType: StockMovementType, id: string): Promise<StockMovementRecord> {
    const response = await axiosClient.get<ApiResponse<{ item: StockMovementRecord }>>(
      endpointsFor(movementType).BY_ID(id)
    );
    return response.data.data!.item;
  },

  async getNextDocumentNo(movementType: StockMovementType): Promise<string> {
    const response = await axiosClient.get<ApiResponse<{ documentNo: string }>>(
      endpointsFor(movementType).NEXT_CODE
    );
    return response.data.data!.documentNo;
  },

  async create(movementType: StockMovementType, payload: StockMovementPayload): Promise<StockMovementRecord> {
    const response = await axiosClient.post<ApiResponse<{ item: StockMovementRecord }>>(
      endpointsFor(movementType).LIST,
      payload
    );
    return response.data.data!.item;
  },

  async update(
    movementType: StockMovementType,
    id: string,
    payload: Partial<StockMovementPayload>
  ): Promise<StockMovementRecord> {
    const response = await axiosClient.put<ApiResponse<{ item: StockMovementRecord }>>(
      endpointsFor(movementType).BY_ID(id),
      payload
    );
    return response.data.data!.item;
  },

  async post(movementType: StockMovementType, id: string): Promise<StockMovementRecord> {
    const response = await axiosClient.patch<ApiResponse<{ item: StockMovementRecord }>>(
      endpointsFor(movementType).POST(id)
    );
    return response.data.data!.item;
  },

  async cancel(movementType: StockMovementType, id: string): Promise<StockMovementRecord> {
    const response = await axiosClient.patch<ApiResponse<{ item: StockMovementRecord }>>(
      endpointsFor(movementType).CANCEL(id)
    );
    return response.data.data!.item;
  },

  async delete(movementType: StockMovementType, id: string): Promise<void> {
    await axiosClient.delete(endpointsFor(movementType).BY_ID(id));
  },
};
