import { useEffect, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { UserLayout } from '../../../components/layout/Layout';
import { Button } from '../../../components/ui/Button';
import {
  StockMovementForm,
  emptyStockMovementForm,
  formValuesToPayload,
} from './StockMovementForm';
import { stockMovementService } from '../../../services/stockMovement.service';
import { inventoryProductService } from '../../../services/product.service';
import { inventorySupplierService } from '../../../services/supplier.service';
import { inventoryWarehouseService } from '../../../services/master.service';
import { toast } from '../../../shared/utils/toast';
import { getApiErrorMessage } from '../../../shared/utils/apiError';
import { useFormValidation } from '../../../hooks/useFormValidation';
import {
  getStockMovementValidationSchema,
  validateStockMovementLines,
} from '../../../shared/validation/inventory.validation';
import { ModulePermissionGuard } from '../../../components/common/ModulePermissionGuard';
import { PORTAL_PERMISSION_MODULES } from '../../../shared/constants/portalPermissionModules';
import type { InventorySupplierRecord, InventoryWarehouseRecord } from '../../../shared/types/inventoryMaster.types';
import type { InventoryProductRecord, StockMovementFormValues, StockMovementType } from '../../../shared/types/inventoryProduct.types';

const configFor = (movementType: StockMovementType) => {
  if (movementType === 'in') {
    return {
      listPath: '/stock-in',
      viewPath: (id: string) => `/stock-in/${id}`,
      perm: PORTAL_PERMISSION_MODULES.stockIn,
      title: 'New Stock In',
      subtitle: 'Create a draft stock in document',
      moduleLabel: 'Stock in',
    };
  }
  return {
    listPath: '/stock-out',
    viewPath: (id: string) => `/stock-out/${id}`,
    perm: PORTAL_PERMISSION_MODULES.stockOut,
    title: 'New Stock Out',
    subtitle: 'Create a draft stock out document',
    moduleLabel: 'Stock out',
  };
};

export const StockMovementCreatePage = ({ movementType }: { movementType: StockMovementType }) => {
  const navigate = useNavigate();
  const config = configFor(movementType);
  const [form, setForm] = useState<StockMovementFormValues>(emptyStockMovementForm());
  const [warehouses, setWarehouses] = useState<InventoryWarehouseRecord[]>([]);
  const [suppliers, setSuppliers] = useState<InventorySupplierRecord[]>([]);
  const [products, setProducts] = useState<InventoryProductRecord[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isGeneratingCode, setIsGeneratingCode] = useState(false);
  const [autoDocumentNo, setAutoDocumentNo] = useState(true);
  const { errors, clearFieldError, clearErrors, validateFields, applyApiErrors } =
    useFormValidation<StockMovementFormValues>();

  useEffect(() => {
    Promise.all([
      inventoryWarehouseService.getActive(),
      movementType === 'in' ? inventorySupplierService.getActive() : Promise.resolve([]),
      inventoryProductService.getActive(),
    ])
      .then(([wh, sup, prod]) => {
        setWarehouses(wh);
        setSuppliers(sup);
        setProducts(prod);
      })
      .catch((err) => toast.error(getApiErrorMessage(err, 'Failed to load master data')));
  }, [movementType]);

  useEffect(() => {
    if (!autoDocumentNo) return;
    setIsGeneratingCode(true);
    stockMovementService
      .getNextDocumentNo(movementType)
      .then((documentNo) => setForm((prev) => ({ ...prev, documentNo })))
      .catch((err) => toast.error(getApiErrorMessage(err, 'Failed to generate document number')))
      .finally(() => setIsGeneratingCode(false));
  }, [autoDocumentNo, movementType]);

  const handleAutoGenerateCode = async () => {
    try {
      setIsGeneratingCode(true);
      setAutoDocumentNo(true);
      const documentNo = await stockMovementService.getNextDocumentNo(movementType);
      setForm((prev) => ({ ...prev, documentNo }));
    } catch (err) {
      toast.error(getApiErrorMessage(err, 'Failed to generate document number'));
    } finally {
      setIsGeneratingCode(false);
    }
  };

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault();
    clearErrors();

    if (!validateFields(form, getStockMovementValidationSchema({ requireDocumentNo: !autoDocumentNo }))) {
      toast.warning('Please fix the highlighted fields.');
      return;
    }

    const lineError = validateStockMovementLines(form.lines);
    if (lineError) {
      toast.warning(lineError);
      return;
    }

    const payload = formValuesToPayload(form, { autoGenerateDocumentNo: autoDocumentNo });

    try {
      setIsSubmitting(true);
      const item = await stockMovementService.create(movementType, payload);
      toast.success('Draft saved. Post the document to update stock.');
      navigate(config.viewPath(item.id));
    } catch (err) {
      toast.error(applyApiErrors(err, 'Failed to create document'));
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <ModulePermissionGuard
      moduleCode={config.perm.moduleCode}
      itemCode={config.perm.itemCode}
      action="create"
      moduleLabel={config.moduleLabel}
    >
      <UserLayout title={config.title} subtitle={config.subtitle}>
        <div className="mb-5">
          <Button type="button" variant="secondary" onClick={() => navigate(config.listPath)}>
            <ArrowLeft className="mr-2 inline h-4 w-4" />
            Back to list
          </Button>
        </div>

        <StockMovementForm
          movementType={movementType}
          value={form}
          errors={errors}
          warehouses={warehouses}
          suppliers={suppliers}
          products={products}
          isSubmitting={isSubmitting}
          autoDocumentNo={autoDocumentNo}
          isGeneratingCode={isGeneratingCode}
          onChange={setForm}
          onClearFieldError={clearFieldError}
          onAutoGenerateCode={handleAutoGenerateCode}
          onDocumentNoManualChange={() => setAutoDocumentNo(false)}
          onCancel={() => navigate(config.listPath)}
          onSubmit={handleSubmit}
          submitLabel="Save draft"
        />
      </UserLayout>
    </ModulePermissionGuard>
  );
};

export const StockInCreatePage = () => <StockMovementCreatePage movementType="in" />;
export const StockOutCreatePage = () => <StockMovementCreatePage movementType="out" />;
