export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/app/auth/login',
    REGISTER: '/app/auth/register',
    LOGOUT: '/app/auth/logout',
    PROFILE: '/app/auth/profile',
    CHANGE_PASSWORD: '/app/auth/change-password',
    FORGOT_PASSWORD: '/app/auth/forgot-password',
    RESEND_OTP: '/app/auth/resend-otp',
    VERIFY_OTP: '/app/auth/verify-otp',
    RESET_PASSWORD: '/app/auth/reset-password',
  },
  MENU: {
    LIST: '/app/menu',
  },
  ROLES: {
    LIST: '/app/roles',
    ACTIVE: '/app/roles/active',
    BY_ID: (id: string) => `/app/roles/${id}`,
  },
  USERS: {
    LIST: '/app/users',
    NEXT_EMPLOYEE_CODE: '/app/users/next-employee-code',
    BY_ID: (id: string) => `/app/users/${id}`,
    DOCUMENTS: (userId: string) => `/app/users/${userId}/documents`,
    DOCUMENT_BY_ID: (userId: string, documentId: string) =>
      `/app/users/${userId}/documents/${documentId}`,
    DOCUMENT_VIEW: (userId: string, documentId: string) =>
      `/app/users/${userId}/documents/${documentId}/view`,
    DOCUMENT_DOWNLOAD: (userId: string, documentId: string) =>
      `/app/users/${userId}/documents/${documentId}/download`,
  },
  PERMISSIONS: {
    LIST: '/app/permissions',
    ME: '/app/permissions/me',
    ROLE: (roleId: string) => `/app/permissions/roles/${roleId}`,
  },
  DEPARTMENTS: {
    LIST: '/app/departments',
    ACTIVE: '/app/departments/active',
    BY_ID: (id: string) => `/app/departments/${id}`,
  },
  DESIGNATIONS: {
    LIST: '/app/designations',
    ACTIVE: '/app/designations/active',
    BY_ID: (id: string) => `/app/designations/${id}`,
  },
  LEAVE_TYPES: {
    LIST: '/app/leave-types',
    ACTIVE: '/app/leave-types/active',
    BY_ID: (id: string) => `/app/leave-types/${id}`,
  },
  LEAVE: {
    LIST: '/app/leave',
    BALANCES: '/app/leave/balances',
    BY_ID: (id: string) => `/app/leave/${id}`,
    REVIEW: (id: string) => `/app/leave/${id}/review`,
    CANCEL: (id: string) => `/app/leave/${id}/cancel`,
  },
  ATTENDANCE: {
    LIST: '/app/attendance',
    SUMMARY: '/app/attendance/summary',
    MY_TODAY: '/app/attendance/my-today',
    MY_RECORDS: '/app/attendance/my-records',
    TEAM_ACCESS: '/app/attendance/team-access',
    CHECK_IN: '/app/attendance/check-in',
    CHECK_OUT: '/app/attendance/check-out',
    DAILY_SHEET: '/app/attendance/daily-sheet',
    MARK: '/app/attendance/mark',
    SETTINGS: '/app/attendance/settings',
    MY_SHIFT: '/app/attendance/my-shift',
    BY_ID: (id: string) => `/app/attendance/${id}`,
  },
  HOLIDAYS: {
    LIST: '/app/holidays',
    ACTIVE: '/app/holidays/active',
    BY_ID: (id: string) => `/app/holidays/${id}`,
  },
  SHIFTS: {
    LIST: '/app/shifts',
    ACTIVE: '/app/shifts/active',
    BY_ID: (id: string) => `/app/shifts/${id}`,
  },
  ANNOUNCEMENTS: {
    LIST: '/app/announcements',
    FEED: '/app/announcements/feed',
    BY_ID: (id: string) => `/app/announcements/${id}`,
  },
  INVENTORY_CATEGORIES: {
    LIST: '/app/inventory-categories',
    ACTIVE: '/app/inventory-categories/active',
    BY_ID: (id: string) => `/app/inventory-categories/${id}`,
  },
  INVENTORY_UNITS: {
    LIST: '/app/inventory-units',
    ACTIVE: '/app/inventory-units/active',
    BY_ID: (id: string) => `/app/inventory-units/${id}`,
  },
  INVENTORY_BRANDS: {
    LIST: '/app/inventory-brands',
    ACTIVE: '/app/inventory-brands/active',
    BY_ID: (id: string) => `/app/inventory-brands/${id}`,
  },
  INVENTORY_WAREHOUSES: {
    LIST: '/app/inventory-warehouses',
    ACTIVE: '/app/inventory-warehouses/active',
    BY_ID: (id: string) => `/app/inventory-warehouses/${id}`,
  },
  INVENTORY_SUPPLIERS: {
    LIST: '/app/inventory-suppliers',
    ACTIVE: '/app/inventory-suppliers/active',
    NEXT_CODE: '/app/inventory-suppliers/next-supplier-code',
    BY_ID: (id: string) => `/app/inventory-suppliers/${id}`,
  },
  INVENTORY_TAXES: {
    LIST: '/app/inventory-taxes',
    ACTIVE: '/app/inventory-taxes/active',
    BY_ID: (id: string) => `/app/inventory-taxes/${id}`,
  },
  PRODUCTS: {
    LIST: '/app/products',
    ACTIVE: '/app/products/active',
    NEXT_CODE: '/app/products/next-product-code',
    BY_ID: (id: string) => `/app/products/${id}`,
  },
  STOCK_IN: {
    LIST: '/app/stock-in',
    NEXT_CODE: '/app/stock-in/next-document-no',
    BY_ID: (id: string) => `/app/stock-in/${id}`,
    POST: (id: string) => `/app/stock-in/${id}/post`,
    CANCEL: (id: string) => `/app/stock-in/${id}/cancel`,
  },
  STOCK_OUT: {
    LIST: '/app/stock-out',
    NEXT_CODE: '/app/stock-out/next-document-no',
    BY_ID: (id: string) => `/app/stock-out/${id}`,
    POST: (id: string) => `/app/stock-out/${id}/post`,
    CANCEL: (id: string) => `/app/stock-out/${id}/cancel`,
  },
  INVENTORY_STOCK: {
    CURRENT: '/app/inventory-stock/current-stock',
    LOW_STOCK: '/app/inventory-stock/current-stock/low',
    LEDGER: '/app/inventory-stock/stock-ledger',
    ADJUSTMENTS: '/app/inventory-stock/stock-adjustments',
    ADJUSTMENT_NEXT: '/app/inventory-stock/stock-adjustments/next-number',
    ADJUSTMENT_BY_ID: (id: string) => `/app/inventory-stock/stock-adjustments/${id}`,
    ADJUSTMENT_APPROVE: (id: string) => `/app/inventory-stock/stock-adjustments/${id}/approve`,
    ADJUSTMENT_CANCEL: (id: string) => `/app/inventory-stock/stock-adjustments/${id}/cancel`,
  },
  CUSTOMERS: {
    LIST: '/app/customers',
    ACTIVE: '/app/customers/active',
    NEXT_CODE: '/app/customers/next-customer-code',
    BY_ID: (id: string) => `/app/customers/${id}`,
  },
  PURCHASE_ORDERS: {
    LIST: '/app/purchase-orders',
    NEXT_NUMBER: '/app/purchase-orders/next-po-number',
    BY_ID: (id: string) => `/app/purchase-orders/${id}`,
    APPROVE: (id: string) => `/app/purchase-orders/${id}/approve`,
    CANCEL: (id: string) => `/app/purchase-orders/${id}/cancel`,
  },
  GRNS: {
    LIST: '/app/grns',
    NEXT_NUMBER: '/app/grns/next-grn-number',
    BY_ID: (id: string) => `/app/grns/${id}`,
    POST: (id: string) => `/app/grns/${id}/post`,
    CANCEL: (id: string) => `/app/grns/${id}/cancel`,
  },
  PURCHASE_RETURNS: {
    LIST: '/app/purchase-returns',
    NEXT_NUMBER: '/app/purchase-returns/next-return-number',
    BY_ID: (id: string) => `/app/purchase-returns/${id}`,
    POST: (id: string) => `/app/purchase-returns/${id}/post`,
    CANCEL: (id: string) => `/app/purchase-returns/${id}/cancel`,
  },
  SALES_ORDERS: {
    LIST: '/app/sales-orders',
    NEXT_NUMBER: '/app/sales-orders/next-so-number',
    BY_ID: (id: string) => `/app/sales-orders/${id}`,
    CONFIRM: (id: string) => `/app/sales-orders/${id}/confirm`,
    CANCEL: (id: string) => `/app/sales-orders/${id}/cancel`,
  },
  DELIVERY_CHALLANS: {
    LIST: '/app/delivery-challans',
    NEXT_NUMBER: '/app/delivery-challans/next-dc-number',
    BY_ID: (id: string) => `/app/delivery-challans/${id}`,
    DISPATCH: (id: string) => `/app/delivery-challans/${id}/dispatch`,
    CANCEL: (id: string) => `/app/delivery-challans/${id}/cancel`,
  },
  SALES_INVOICES: {
    LIST: '/app/sales-invoices',
    NEXT_NUMBER: '/app/sales-invoices/next-invoice-number',
    BY_ID: (id: string) => `/app/sales-invoices/${id}`,
    SEND: (id: string) => `/app/sales-invoices/${id}/send`,
    CANCEL: (id: string) => `/app/sales-invoices/${id}/cancel`,
  },
  SALES_RETURNS: {
    LIST: '/app/sales-returns',
    NEXT_NUMBER: '/app/sales-returns/next-return-number',
    BY_ID: (id: string) => `/app/sales-returns/${id}`,
    POST: (id: string) => `/app/sales-returns/${id}/post`,
    CANCEL: (id: string) => `/app/sales-returns/${id}/cancel`,
  },
  BOMS: {
    LIST: '/app/boms',
    ACTIVE: '/app/boms/active',
    NEXT_CODE: '/app/boms/next-bom-code',
    BY_ID: (id: string) => `/app/boms/${id}`,
    BY_PRODUCT: (productId: string) => `/app/boms/by-product/${productId}`,
  },
  WORK_ORDERS: {
    LIST: '/app/work-orders',
    NEXT_NUMBER: '/app/work-orders/next-wo-number',
    BY_ID: (id: string) => `/app/work-orders/${id}`,
    START: (id: string) => `/app/work-orders/${id}/start`,
    CANCEL: (id: string) => `/app/work-orders/${id}/cancel`,
  },
  MATERIAL_ISSUES: {
    LIST: '/app/material-issues',
    NEXT_NUMBER: '/app/material-issues/next-issue-number',
    BY_ID: (id: string) => `/app/material-issues/${id}`,
    ISSUE: (id: string) => `/app/material-issues/${id}/issue`,
    CANCEL: (id: string) => `/app/material-issues/${id}/cancel`,
  },
  PRODUCTION_ENTRIES: {
    LIST: '/app/production-entries',
    NEXT_NUMBER: '/app/production-entries/next-entry-number',
    BY_ID: (id: string) => `/app/production-entries/${id}`,
    POST: (id: string) => `/app/production-entries/${id}/post`,
    CANCEL: (id: string) => `/app/production-entries/${id}/cancel`,
  },
  NOTIFICATIONS: {
    LIST: '/app/notifications',
    UNREAD_COUNT: '/app/notifications/unread-count',
    READ_ALL: '/app/notifications/read-all',
    READ: (id: string) => `/app/notifications/${id}/read`,
  },
  SUBSCRIPTION: {
    CURRENT: '/app/subscription/current',
    PLANS: '/app/subscription/plans',
    QUOTE_UPGRADE: '/app/subscription/quote/upgrade',
    QUOTE_RENEW: '/app/subscription/quote/renew',
    UPGRADE: '/app/subscription/upgrade',
    RENEW: '/app/subscription/renew',
    AUTO_RENEW: '/app/subscription/auto-renew',
  },
  PAYMENTS: {
    CHECKOUT: '/app/payments/checkout',
    VERIFY: '/app/payments/verify',
    HISTORY: '/app/payments/history',
  },
  ASSISTANT: {
    CHAT: '/app/assistant/chat',
  },
  REPORTS: {
    USERS: '/app/reports/users',
    ATTENDANCE: '/app/reports/attendance',
    PRODUCTS: '/app/reports/products',
    STOCK_IN: '/app/reports/stock-in',
    STOCK_OUT: '/app/reports/stock-out',
    CURRENT_STOCK: '/app/reports/current-stock',
    STOCK_LEDGER: '/app/reports/stock-ledger',
    STOCK_ADJUSTMENTS: '/app/reports/stock-adjustments',
  },
} as const;

export const QUERY_KEYS = {
  AUTH: 'auth',
  MENU: 'menu',
} as const;
