import {
  LayoutDashboard,
  Package,
  ClipboardList,
  Users,
  Building2,
  Receipt,
  Boxes,
  Layers,
  ListTree,
  Globe,
  Map,
  MapPin,
  CreditCard,
  CalendarDays,
  CalendarCheck,
  Clock,
  Megaphone,
  ArrowDownToLine,
  ArrowUpFromLine,
  ShoppingCart,
  Truck,
  FileText,
  RotateCcw,
  UserSquare2,
  Factory,
  ClipboardCheck,
  PackagePlus,
  PackageMinus,
  type LucideIcon,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  inventory: Package,
  products: Package,
  product: Package,
  'stock-in': ArrowDownToLine,
  stockin: ArrowDownToLine,
  'stock-out': ArrowUpFromLine,
  stockout: ArrowUpFromLine,
  'current-stock': Package,
  'stock-ledger': ClipboardList,
  'stock-adjustment': ClipboardList,
  // Purchase
  purchase: ShoppingCart,
  'purchase-orders': ShoppingCart,
  grns: ArrowDownToLine,
  'purchase-returns': RotateCcw,
  // Sales
  sales: Truck,
  'sales-orders': ClipboardList,
  'delivery-challans': Truck,
  'sales-invoices': Receipt,
  'sales-returns': RotateCcw,
  invoices: Receipt,
  // Manufacturing
  manufacturing: Factory,
  'boms': ClipboardCheck,
  bom: ClipboardCheck,
  'work-orders': Factory,
  'work-order': Factory,
  'material-issues': PackageMinus,
  'material-issue': PackageMinus,
  'production-entries': PackagePlus,
  'production-entry': PackagePlus,
  // Others
  orders: ClipboardList,
  customers: UserSquare2,
  customer: UserSquare2,
  documents: FileText,
  users: Users,
  user: Users,
  companies: Building2,
  subscriptions: Receipt,
  modules: Boxes,
  'module-groups': Layers,
  'module-items': ListTree,
  countries: Globe,
  states: Map,
  cities: MapPin,
  plans: CreditCard,
  leave: CalendarDays,
  leaves: CalendarDays,
  'leave-types': CalendarCheck,
  attendance: Clock,
  announcements: Megaphone,
  announcement: Megaphone,
  master: Boxes,
};

export const getModuleIcon = (code: string): LucideIcon => {
  return ICON_MAP[code] ?? Boxes;
};
