import { useEffect, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { UserLayout } from '../../../components/layout/Layout';
import { Button } from '../../../components/ui/Button';
import { DeliveryChallanForm, emptyDeliveryChallanForm, formValuesToDcPayload } from './DeliveryChallanForm';
import { deliveryChallanService } from '../../../services/trading.service';
import { useTradingMasters } from '../purchase/useTradingMasters';
import { toast } from '../../../shared/utils/toast';
import { getApiErrorMessage } from '../../../shared/utils/apiError';
import { useFormValidation } from '../../../hooks/useFormValidation';
import { ModulePermissionGuard } from '../../../components/common/ModulePermissionGuard';
import { PORTAL_PERMISSION_MODULES } from '../../../shared/constants/portalPermissionModules';
import type { DeliveryChallanFormValues } from '../../../shared/types/trading.types';

const LIST_PATH = '/sales/delivery-challans';
const PERM = PORTAL_PERMISSION_MODULES.deliveryChallans;

export const DeliveryChallanCreatePage = () => {
  const navigate = useNavigate();
  const [form, setForm] = useState<DeliveryChallanFormValues>(emptyDeliveryChallanForm());
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isGeneratingNumber, setIsGeneratingNumber] = useState(false);
  const [autoDcNumber, setAutoDcNumber] = useState(true);
  const { errors, clearFieldError, clearErrors, applyApiErrors } = useFormValidation<DeliveryChallanFormValues>();
  const masters = useTradingMasters();

  useEffect(() => {
    if (!autoDcNumber) return;
    setIsGeneratingNumber(true);
    deliveryChallanService.getNextDcNumber()
      .then((dcNumber) => setForm((prev) => ({ ...prev, dcNumber })))
      .catch((err) => toast.error(getApiErrorMessage(err, 'Failed to generate DC number')))
      .finally(() => setIsGeneratingNumber(false));
  }, [autoDcNumber]);

  const handleAutoGenerateNumber = async () => {
    try {
      setIsGeneratingNumber(true); setAutoDcNumber(true);
      const dcNumber = await deliveryChallanService.getNextDcNumber();
      setForm((prev) => ({ ...prev, dcNumber }));
    } catch (err) { toast.error(getApiErrorMessage(err, 'Failed to generate DC number')); }
    finally { setIsGeneratingNumber(false); }
  };

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault(); clearErrors();
    if (!form.customerId) { toast.warning('Please select a customer.'); return; }
    if (!form.warehouseId) { toast.warning('Please select a warehouse.'); return; }
    if (form.lines.length === 0) { toast.warning('Please add at least one product line.'); return; }
    try {
      setIsSubmitting(true);
      const record = await deliveryChallanService.create(formValuesToDcPayload(form, { autoGenerateDcNumber: autoDcNumber }));
      toast.success('Delivery challan created.');
      navigate(`${LIST_PATH}/${record.id}`);
    } catch (err) { toast.error(applyApiErrors(err, 'Failed to create challan')); }
    finally { setIsSubmitting(false); }
  };

  return (
    <ModulePermissionGuard moduleCode={PERM.moduleCode} itemCode={PERM.itemCode} action="create" moduleLabel="Delivery Challans">
      <UserLayout title="New Delivery Challan" subtitle="Dispatch goods to a customer">
        <div className="mb-5">
          <Button type="button" variant="secondary" onClick={() => navigate(LIST_PATH)}>
            <ArrowLeft className="mr-2 inline h-4 w-4" />Back to Challans
          </Button>
        </div>
        {masters.isLoading ? <div className="flex h-64 items-center justify-center text-muted">Loading...</div> : (
          <DeliveryChallanForm mode="create" value={form} errors={errors} isSubmitting={isSubmitting}
            autoDcNumber={autoDcNumber} isGeneratingNumber={isGeneratingNumber}
            customers={masters.customers} warehouses={masters.warehouses} products={masters.products} taxes={masters.taxes}
            onChange={setForm} onClearFieldError={clearFieldError} onAutoGenerateNumber={handleAutoGenerateNumber}
            onDcNumberManualChange={() => setAutoDcNumber(false)} onCancel={() => navigate(LIST_PATH)} onSubmit={handleSubmit} submitLabel="Save draft" />
        )}
      </UserLayout>
    </ModulePermissionGuard>
  );
};
